image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install dotnet-sdk

build:
  project: WinPath.csproj
  verbosity: minimal

test_script:
- OpenCover.Console.exe -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:".\bin\Debug\WinPath.dll -noshadow" -output:".\WinPath_coverage.xml" -oldstyle
- codecov -f "WinPath_coverage.xml.xml"
- curl -s https://codecov.io/bash > codecov
- chmod +x codecov
- codecov -f "MyProject_coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
