image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install dotnet-sdk

build:
  project: WinPath.csproj
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\WinPath.Tests\bin\Debug\WinPath.dll -noshadow" -output:".\WinPath_coverage.xml" -oldstyle
# OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "WinPath_coverage.xml"
- curl -s https://codecov.io/bash > codecov
- chmod +x codecov
- codecov -f "WinPath_coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
