image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install dotnet-sdk
- choco install dotnet

build:
  project: WinPath.sln
  verbosity: minimal

test_script:
- cp "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Runtime.dll" "%xunit20%\"
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\bin\WinPath.Tests\Debug\net5.0\WinPath.Tests.dll -noshadow" -output:".\WinPath_coverage.xml" -oldstyle
# OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "WinPath_coverage.xml"
- curl -s https://codecov.io/bash > codecov
- chmod +x codecov
- codecov -f "WinPath_coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}\
