codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 15%
        base: auto
        paths: 
          - "./WinPath/"
          - "./WinPath.Library/"
        if_ci_failed: ignore #success, failure, error, ignore
        informational: false
        only_pulls: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
