name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    #strategy:
    #  matrix:
    #    dotnet: [ '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' #${{ matrix.dotnet }}
    - name: Add nuget.org as a source
      run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
    - name: Clear cache
      shell: cmd
      run: dotnet clean ./WinPath.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Publish script
      run: dotnet publish -c Release -r win10-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=false -p:UseAppHost=true --self-contained false
    - name: Test
      run: dotnet test --no-build --verbosity normal
